import {
  describeRelationship,
  isProcedure,
  programStepOpMeta,
  type CustomType,
  type Derivation,
  type Diagram,
  type DiagramExtension,
  type Dialect,
  type Program,
  type ProgramStep,
  type Relationship,
  type Table,
} from '@shared/types';
import { createColumn, createCustomTypeField, createDerivation, createExtension, createIndex, createProgram, createProgramStep, createRelationship, createTable } from '../model';
import { newId } from '../ids';
import { readAnnotations, type AnnotatedConnection, type AnnotatedProgram, type SqlAnnotations } from './annotations';
import { parseSql, type ParseResult, type ParsedRoutine, type ParsedTable } from './parser';
import { createProcedureParam, proceduresFromRoutines } from '../procedures';

export interface ImportResult {
  tables: Table[];
  relationships: Relationship[];
  customTypes: CustomType[];
  extensions: DiagramExtension[];
  /** Programs the annotation block carried; empty for a script without one. */
  programs: Program[];
  errors: string[];
  warnings: string[];
  statementCount: number;
}

/**
 * Turn a parser result into diagram tables and relationships (ids assigned,
 * positions in a grid). `annotations` is the connection metadata a script
 * generated by this app carries in its trailing comments; it restores the
 * connections DDL cannot express and the SQL tagged onto the ones it can.
 */
export function parseResultToDiagram(res: ParseResult, existing: Diagram | null = null, annotations: SqlAnnotations | null = null): ImportResult {
  const warnings = res.warnings.map((w) => `line ${w.line}: ${w.message}`);
  const errors = res.errors.map((e) => `line ${e.line}:${e.col}: ${e.message}`);
  const tables: Table[] = [];
  const relationships: Relationship[] = [];
  const byName = new Map<string, Table>();
  const existingNames = new Set((existing?.tables ?? []).map((t) => t.name.toLowerCase()));

  const keyOf = (name: string) => name.toLowerCase();

  for (const pt of res.tables) {
    const t = parsedTableToTable(pt);
    if (existingNames.has(keyOf(t.name))) warnings.push(`Table ${t.name} already exists in the diagram; the imported copy was renamed.`);
    let name = t.name;
    let i = 2;
    while (existingNames.has(keyOf(name)) || byName.has(keyOf(name))) name = `${t.name}_${i++}`;
    t.name = name;
    byName.set(keyOf(pt.name), t);
    tables.push(t);
  }

  // Referenced tables that are not defined get a stub so the relationship can be drawn.
  const ensureTarget = (refName: string, refColumns: string[], from: string): Table => {
    const key = keyOf(refName);
    let target = byName.get(key);
    if (target) return target;
    const fromExisting = existing?.tables.find((t) => keyOf(t.name) === key);
    if (fromExisting) return fromExisting;
    warnings.push(`Table ${refName} is referenced by ${from} but not defined; a placeholder table was created.`);
    target = createTable({ name: refName, comment: `Placeholder created for a reference from ${from}` });
    for (const c of refColumns.length ? refColumns : ['id']) {
      target.columns.push(createColumn({ name: c, type: 'INTEGER', primaryKey: true, nullable: false }));
    }
    byName.set(key, target);
    tables.push(target);
    return target;
  };

  for (const pt of res.tables) {
    const src = byName.get(keyOf(pt.name))!;
    const fks = [...pt.foreignKeys];
    for (const c of pt.columns) {
      if (c.references) fks.push({ ...c.references, columns: [c.name] });
    }
    for (const fk of fks) {
      const target = ensureTarget(fk.refTable, fk.refColumns, pt.name);
      const sourceColumnIds = fk.columns.map((n) => src.columns.find((c) => c.name === n)?.id).filter((x): x is string => Boolean(x));
      let refCols = fk.refColumns;
      if (refCols.length === 0) refCols = target.columns.filter((c) => c.primaryKey).map((c) => c.name);
      const targetColumnIds = refCols.map((n) => target.columns.find((c) => c.name === n)?.id).filter((x): x is string => Boolean(x));
      if (sourceColumnIds.length === 0 || targetColumnIds.length === 0) {
        warnings.push(`Foreign key on ${pt.name} (${fk.columns.join(', ')}) could not be matched to columns and was skipped.`);
        continue;
      }
      relationships.push(
        createRelationship({
          kind: 'fk',
          name: fk.name,
          sourceTableId: src.id,
          sourceColumnIds,
          targetTableId: target.id,
          targetColumnIds,
          onDelete: fk.onDelete,
          onUpdate: fk.onUpdate,
        }),
      );
    }
  }

  // Views: a table of kind 'view' whose inputs are flow links from the tables it reads.
  for (const pv of res.views) {
    const view = createTable({ name: pv.name, schema: pv.schema, kind: 'view', viewSql: pv.sql, materialized: pv.materialized || undefined });
    if (existingNames.has(keyOf(view.name)) || byName.has(keyOf(view.name))) {
      warnings.push(`View ${pv.name} clashes with an existing table name; the imported copy was renamed.`);
      let i = 2;
      while (existingNames.has(keyOf(view.name)) || byName.has(keyOf(view.name))) view.name = `${pv.name}_${i++}`;
    }
    for (const c of pv.columns) view.columns.push(createColumn({ name: c, type: 'TEXT', nullable: true }));
    byName.set(keyOf(pv.name), view);
    tables.push(view);
  }
  for (const pv of res.views) {
    const view = byName.get(keyOf(pv.name));
    if (!view) continue;
    for (const src of pv.sources) {
      const bare = src.includes('.') ? src.slice(src.lastIndexOf('.') + 1) : src;
      const source = byName.get(keyOf(bare)) ?? existing?.tables.find((t) => keyOf(t.name) === keyOf(bare));
      if (!source || source.id === view.id) continue;
      if (relationships.some((r) => r.kind === 'flow' && r.sourceTableId === source.id && r.targetTableId === view.id)) continue;
      relationships.push(createRelationship({ kind: 'flow', name: 'view source', sourceTableId: source.id, sourceColumnIds: [], targetTableId: view.id, targetColumnIds: [] }));
    }
  }

  // Connections the DDL could not carry: the annotation block at the end of a
  // script this app wrote is the only place they exist.
  const lookupTable = (name: string) => byName.get(keyOf(name)) ?? existing?.tables.find((t) => keyOf(t.name) === keyOf(name));
  const programs: Program[] = [];
  if (annotations) {
    applyAnnotations(annotations.connections, lookupTable, relationships, existing, warnings);
    programs.push(...restorePrograms(annotations.programs ?? [], lookupTable, warnings));
  }

  // Procedures. The CREATE statement is the truth for what the routine is —
  // its parameters, return type and body — and the annotation block, when the
  // script has one, for how it was drawn: the steps someone arranged by hand
  // are kept rather than read out of the body again. A routine with no
  // annotation gets its steps from its body.
  const routines = res.routines ?? [];
  if (routines.length) {
    const annotated = new Map(programs.filter(isProcedure).map((p) => [p.name.toLowerCase(), p] as const));
    const fresh: ParsedRoutine[] = [];
    for (const r of routines) {
      const hit = annotated.get(r.name.toLowerCase());
      if (!hit) {
        fresh.push(r);
        continue;
      }
      const [def] = proceduresFromRoutines([r], lookupTable);
      hit.params = def.params;
      if (def.schema) hit.schema = def.schema;
      if (def.returns) hit.returns = def.returns;
      else delete hit.returns;
      if (def.routineLanguage) hit.routineLanguage = def.routineLanguage;
      hit.body = def.body;
      if (def.comment) hit.comment = def.comment;
    }
    const existingNames = new Set([...(existing?.programs ?? []), ...programs].filter(isProcedure).map((p) => p.name.toLowerCase()));
    const made = proceduresFromRoutines(fresh, lookupTable, [...(existing?.programs ?? []), ...programs]);
    for (const p of made) {
      if (existingNames.has(p.name.toLowerCase())) warnings.push(`A procedure called ${p.name} is already in the diagram; the imported one sits beside it.`);
      programs.push(p);
    }
  }

  // simple grid so tables never stack before the user runs auto-layout
  const cols = Math.max(1, Math.ceil(Math.sqrt(tables.length)));
  tables.forEach((t, i) => {
    t.position = { x: (i % cols) * 320, y: Math.floor(i / cols) * 260 };
  });

  const existingTypeNames = new Set((existing?.customTypes ?? []).map((t) => t.name.toLowerCase()));
  const customTypes: CustomType[] = [];
  for (const e of res.enums) {
    if (existingTypeNames.has(e.name.toLowerCase())) {
      warnings.push(`Type ${e.name} already exists in the diagram; the imported enum was skipped.`);
      continue;
    }
    customTypes.push({ id: newId('ctype'), name: e.name, kind: 'enum', values: e.values });
  }
  for (const c of res.compositeTypes) {
    if (existingTypeNames.has(c.name.toLowerCase())) {
      warnings.push(`Type ${c.name} already exists in the diagram; the imported type was skipped.`);
      continue;
    }
    customTypes.push({
      id: newId('ctype'),
      name: c.name,
      kind: 'composite',
      fields: c.fields.map((f) => createCustomTypeField({ name: f.name, type: f.type })),
    });
  }

  // The engine keys an extension by name, so one already declared is the same
  // one: keep the diagram's entry (it may carry a comment) rather than adding a twin.
  const existingExtensions = new Set((existing?.extensions ?? []).map((e) => e.name.trim().toLowerCase()));
  const extensions: DiagramExtension[] = [];
  for (const e of res.extensions) {
    if (existingExtensions.has(e.name.toLowerCase())) continue;
    existingExtensions.add(e.name.toLowerCase());
    extensions.push(createExtension({ name: e.name, schema: e.schema, version: e.version }));
  }

  return { tables, relationships, customTypes, extensions, programs, errors, warnings, statementCount: res.statementCount };
}

/** Same columns, in any order: two ends of a foreign key are a set, not a sequence. */
function sameColumnSet(a: string[], b: string[]): boolean {
  if (a.length !== b.length) return false;
  const set = new Set(a);
  return b.every((id) => set.has(id));
}

/**
 * Put back the connections a generated script carries in its annotation block.
 *
 * A connection the DDL already created is enriched rather than duplicated: the
 * constraint says who points at whom and what happens on delete, the block says
 * how it reads in English and what SQL was tagged onto it. Everything the DDL
 * has no syntax for — a data flow and its derived columns, a serialized copy, a
 * dependency — exists only in the block, and is created here.
 *
 * Tables and columns are matched by name, so an end the script does not define
 * and the diagram does not have is reported rather than invented: a placeholder
 * table is right for a foreign key (the reference proves the table exists), and
 * wrong for an annotation, which is only ever a description of something else.
 */
function applyAnnotations(
  connections: AnnotatedConnection[],
  lookup: (name: string) => Table | undefined,
  relationships: Relationship[],
  existing: Diagram | null,
  warnings: string[],
): void {
  const columnId = (t: Table, name: string) => t.columns.find((c) => c.name.toLowerCase() === name.toLowerCase())?.id;
  const columnIds = (t: Table, names: string[] | undefined) => (names ?? []).map((n) => columnId(t, n)).filter((x): x is string => Boolean(x));
  // One relationship answers to one annotation. Two data flows between the same
  // pair of tables look alike from the outside, and without this the second
  // would enrich the first instead of becoming a connection of its own.
  const claimed = new Set<Relationship>();

  for (const a of connections) {
    const src = lookup(a.from);
    const tgt = lookup(a.to);
    if (!src || !tgt) {
      const missing = [!src ? a.from : null, !tgt ? a.to : null].filter(Boolean).join(' and ');
      warnings.push(`Connection ${a.from} → ${a.to} was not restored: ${missing} is neither in this script nor in the diagram.`);
      continue;
    }

    const sourceColumnIds = columnIds(src, a.fromColumns);
    const targetColumnIds = columnIds(tgt, a.toColumns);
    const sentence = describeRelationship(a, src.name, tgt.name);

    const derivations: Derivation[] = [];
    for (const dv of a.derivations ?? []) {
      const targetColumnId = columnId(tgt, dv.target);
      if (!targetColumnId) {
        warnings.push(`The derived column ${dv.target} of "${sentence}" was skipped: ${tgt.name} has no column called ${dv.target}.`);
        continue;
      }
      derivations.push(
        createDerivation({
          targetColumnId,
          expression: dv.expression,
          groupBy: [...(dv.groupBy ?? [])],
          ...(dv.aggregate ? { aggregate: dv.aggregate } : {}),
          ...(dv.filter ? { filter: dv.filter } : {}),
          ...(dv.window ? { window: { fn: dv.window.fn, orderBy: [...(dv.window.orderBy ?? [])], partitionBy: [...(dv.window.partitionBy ?? [])] } } : {}),
        }),
      );
    }

    // The same two tables can be joined by several connections, so a match has
    // to agree on the columns too — except where the block names columns the
    // imported table no longer has, when the ends are all there is to go on.
    const matches = (r: Relationship) =>
      r.kind === a.kind &&
      r.sourceTableId === src.id &&
      r.targetTableId === tgt.id &&
      (sourceColumnIds.length === 0 || r.sourceColumnIds.length === 0 || sameColumnSet(r.sourceColumnIds, sourceColumnIds));

    const found = relationships.find((r) => !claimed.has(r) && matches(r));
    if (found) {
      claimed.add(found);
      if (a.verb) found.verb = a.verb;
      if (a.name) found.name = a.name;
      if (a.inverseName) found.inverseName = a.inverseName;
      // The DDL is the authority on what the database really does; the block
      // only fills in what the constraint did not say.
      if (a.onDelete && (!found.onDelete || found.onDelete === 'NO ACTION')) found.onDelete = a.onDelete;
      if (a.onUpdate && (!found.onUpdate || found.onUpdate === 'NO ACTION')) found.onUpdate = a.onUpdate;
      if (a.query) found.query = a.query;
      if (a.note) found.note = a.note;
      if (derivations.length) found.derivations = derivations;
      continue;
    }
    if (existing?.relationships.some(matches)) {
      warnings.push(`"${sentence}" is already in the diagram; it was not added again.`);
      continue;
    }

    const made = createRelationship({
      kind: a.kind,
      verb: a.verb,
      sourceTableId: src.id,
      sourceColumnIds,
      targetTableId: tgt.id,
      targetColumnIds,
      name: a.name,
      inverseName: a.inverseName,
      onDelete: a.onDelete ?? 'NO ACTION',
      onUpdate: a.onUpdate ?? 'NO ACTION',
      query: a.query,
      note: a.note,
      ...(derivations.length ? { derivations } : {}),
    });
    claimed.add(made);
    relationships.push(made);
  }
}

/**
 * Put back the programs a generated script carries in its annotation block,
 * and the code inside them.
 *
 * A step naming a table the script does not define and the diagram does not
 * have keeps everything except the pointer: its op, its SQL, its code and its
 * note all survive, and the linter reports the missing table afterwards. That
 * is the opposite of how a connection is handled, on purpose — a connection
 * with a missing end describes nothing, while a step with a missing table is
 * still the code somebody wrote. A call whose target the block never listed is
 * kept on the same terms.
 *
 * Containment and call targets are written as paths, so they are resolved in a
 * second pass once every node has an id: the block lists nodes in diagram
 * order, and a member may well come before the module it sits in.
 */
function restorePrograms(annotated: AnnotatedProgram[], lookup: (name: string) => Table | undefined, warnings: string[]): Program[] {
  const out: Program[] = [];
  const byPath = new Map<string, Program>();
  const pending: { node: Program; parent?: string; targets: { step: ProgramStep; target?: string }[] }[] = [];
  for (const a of annotated) {
    const targets: { step: ProgramStep; target?: string }[] = [];
    const steps = a.steps.map((s) => {
      const meta = programStepOpMeta(s.op);
      const table = meta.touchesDatabase && s.table ? lookup(s.table) : undefined;
      if (meta.touchesDatabase && s.table && !table) {
        warnings.push(`Step "${s.op} ${s.table}" of the program ${a.name} kept its SQL and code, but ${s.table} is neither in this script nor in the diagram.`);
      }
      const columnIds = table ? (s.columns ?? []).map((n) => table.columns.find((c) => c.name.toLowerCase() === n.toLowerCase())?.id).filter((x): x is string => Boolean(x)) : [];
      const step = createProgramStep({
        op: s.op,
        ...(table ? { tableId: table.id } : {}),
        columnIds,
        ...(s.sql ? { sql: s.sql } : {}),
        ...(s.code ? { code: s.code } : {}),
        ...(s.note ? { note: s.note } : {}),
      });
      if (meta.namesCode) targets.push({ step, target: s.target });
      return step;
    });
    const node = createProgram({
      name: a.name,
      ...(a.kind ? { kind: a.kind } : {}),
      ...(a.collapsed ? { collapsed: true } : {}),
      language: a.language,
      ...(a.role ? { role: a.role } : {}),
      ...(a.entrypoint ? { entrypoint: a.entrypoint } : {}),
      ...(a.comment ? { comment: a.comment } : {}),
      ...(a.source ? { source: a.source } : {}),
      steps,
      ...(a.kind === 'procedure' && a.routine
        ? {
            ...(a.routine.schema ? { schema: a.routine.schema } : {}),
            ...(a.routine.params?.length ? { params: a.routine.params.map((x) => createProcedureParam(x)) } : {}),
            ...(a.routine.returns ? { returns: a.routine.returns } : {}),
            ...(a.routine.language ? { routineLanguage: a.routine.language } : {}),
            ...(a.routine.body ? { body: a.routine.body } : {}),
          }
        : {}),
    });
    byPath.set((a.parent ? `${a.parent}/${a.name}` : a.name).toLowerCase(), node);
    pending.push({ node, parent: a.parent, targets });
    out.push(node);
  }
  const find = (path: string | undefined): Program | undefined => {
    if (!path) return undefined;
    const exact = byPath.get(path.toLowerCase());
    if (exact) return exact;
    const tail = path.slice(path.lastIndexOf('/') + 1).toLowerCase();
    const byName = out.filter((p) => p.name.toLowerCase() === tail);
    return byName.length === 1 ? byName[0] : undefined;
  };
  for (const { node, parent, targets } of pending) {
    const container = find(parent);
    if (container && container !== node) node.parentId = container.id;
    else if (parent) warnings.push(`${node.name} was inside ${parent}, which this script does not describe, so it stands at the top level.`);
    for (const { step, target } of targets) {
      const hit = find(target);
      if (hit) step.codeId = hit.id;
      else if (target) warnings.push(`Step "${step.op} ${target}" of ${node.name} kept its code, but ${target} is not in this script.`);
    }
  }
  return out;
}

function parsedTableToTable(pt: ParsedTable): Table {
  const t = createTable({
    name: pt.name,
    // A temporary table lives in the session's own schema (pg_temp, temp); that is where it is, not a schema it belongs to.
    schema: pt.storage === 'temporary' && pt.schema && /^(pg_temp\w*|temp)$/i.test(pt.schema) ? undefined : pt.schema,
    comment: pt.comment,
    storage: pt.storage,
    // PRESERVE ROWS is the default, so only the two that change something are kept.
    onCommit: pt.storage === 'temporary' && pt.onCommit !== 'preserve' ? pt.onCommit : undefined,
  });
  for (const pc of pt.columns) {
    let defaultValue = pc.defaultValue;
    let autoIncrement = pc.autoIncrement;
    if (defaultValue && /^nextval\s*\(/i.test(defaultValue)) {
      autoIncrement = true;
      defaultValue = undefined;
    }
    t.columns.push(
      createColumn({
        name: pc.name,
        type: pc.type,
        nullable: pc.nullable,
        primaryKey: pc.primaryKey,
        unique: pc.unique,
        autoIncrement,
        defaultValue,
        check: pc.check,
        comment: pc.comment,
      }),
    );
  }
  const idFor = (name: string) => t.columns.find((c) => c.name === name)?.id;
  for (const u of pt.uniques) {
    const ids = u.columns.map(idFor).filter((x): x is string => Boolean(x));
    if (ids.length) t.indexes.push(createIndex({ name: u.name ?? '', columnIds: ids, unique: true }));
  }
  for (const idx of pt.indexes) {
    const ids = idx.columns.map(idFor).filter((x): x is string => Boolean(x));
    if (ids.length) t.indexes.push(createIndex({ name: idx.name ?? '', columnIds: ids, unique: idx.unique }));
  }
  t.checks = [...pt.checks];
  return t;
}

/**
 * Convenience: parse + convert in one call, connection metadata included.
 *
 * The tokenizer drops comments, so the annotation block is read straight off
 * the text rather than out of the parse; a script without one imports exactly
 * as it always did.
 */
export interface ImportOptions {
  /**
   * A table or view the diagram already has by name is left as it is rather
   * than imported again as a renamed copy; references to it land on the one
   * the diagram has. For a paste that restates part of the schema around the
   * thing it is really about.
   */
  keepExisting?: boolean;
  /** Routines not to import, by name: one the caller is reading into a procedure of its own. */
  skipRoutines?: string[];
}

export function importSql(sql: string, dialect: Dialect, existing: Diagram | null = null, opts: ImportOptions = {}): ImportResult {
  const { annotations, error } = readAnnotations(sql);
  let parsed = parseSql(sql, dialect);
  const had = new Set(opts.keepExisting ? (existing?.tables ?? []).map((t) => t.name.toLowerCase()) : []);
  const skip = new Set((opts.skipRoutines ?? []).map((n) => n.toLowerCase()));
  const keptTables = parsed.tables.filter((t) => had.has(t.name.toLowerCase())).map((t) => t.name);
  const keptViews = parsed.views.filter((v) => had.has(v.name.toLowerCase())).map((v) => v.name);
  if (had.size || skip.size) {
    parsed = {
      ...parsed,
      tables: parsed.tables.filter((t) => !had.has(t.name.toLowerCase())),
      views: parsed.views.filter((v) => !had.has(v.name.toLowerCase())),
      routines: (parsed.routines ?? []).filter((r) => !skip.has(r.name.toLowerCase())),
    };
  }
  const res = parseResultToDiagram(parsed, existing, annotations);
  const kept = [...keptTables, ...keptViews];
  if (kept.length) res.warnings.push(`${kept.join(', ')} ${kept.length === 1 ? 'is' : 'are'} already in the diagram and ${kept.length === 1 ? 'was' : 'were'} kept as ${kept.length === 1 ? 'it is' : 'they are'}.`);
  if (error) res.warnings.push(error);
  return res;
}
