import { describe, expect, it } from 'vitest';
import type { Diagram } from '../src/shared/types';
import { generateDropStatements, generateSchema, generateTableSql, orderTables } from '../src/lib/sql/generator';
import { importSql } from '../src/lib/sql/import';
import { parseSql } from '../src/lib/sql/parser';
import { translateType } from '../src/lib/sql/dialect';
import { emptyDiagram, createRelationship } from '../src/lib/model';

function diagramFrom(sql: string, dialect: Diagram['dialect']): Diagram {
  const d = emptyDiagram(dialect, 'test');
  const r = importSql(sql, dialect);
  d.tables = r.tables;
  d.relationships = r.relationships;
  return d;
}

const SHOP = `
CREATE TABLE customers (id SERIAL PRIMARY KEY, email VARCHAR(255) NOT NULL UNIQUE);
CREATE TABLE orders (
  id BIGSERIAL PRIMARY KEY,
  customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  total NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (total >= 0)
);
CREATE INDEX idx_orders_customer ON orders (customer_id);
COMMENT ON TABLE orders IS 'Orders';
`;

describe('generateSchema', () => {
  it('emits PostgreSQL DDL in dependency order with inline foreign keys', () => {
    const d = diagramFrom(SHOP, 'postgresql');
    const out = generateSchema(d);
    expect(out.warnings).toEqual([]);
    const script = out.script;
    expect(script.indexOf('CREATE TABLE customers')).toBeLessThan(script.indexOf('CREATE TABLE orders'));
    expect(script).toContain('id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
    expect(script).toContain('id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
    expect(script).toContain('email VARCHAR(255) NOT NULL UNIQUE');
    expect(script).toContain('total NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (total >= 0)');
    expect(script).toContain('FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE');
    expect(script).toContain('CREATE INDEX idx_orders_customer ON orders (customer_id);');
    expect(script).toContain("COMMENT ON TABLE orders IS 'Orders';");
    expect(script).not.toContain('ALTER TABLE');
  });

  it('emits MariaDB DDL with AUTO_INCREMENT, inline keys and table options', () => {
    const d = diagramFrom(SHOP, 'postgresql');
    d.dialect = 'mariadb';
    for (const t of d.tables) for (const c of t.columns) c.type = translateType(c.type, 'postgresql', 'mariadb');
    const out = generateSchema(d);
    expect(out.script).toContain('CREATE TABLE customers (');
    expect(out.script).toContain('id INT NOT NULL AUTO_INCREMENT PRIMARY KEY');
    expect(out.script).toContain('id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY');
    expect(out.script).toContain('KEY idx_orders_customer (customer_id)');
    expect(out.script).toContain("ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Orders';");
    expect(out.script).not.toContain('COMMENT ON');
  });

  it('round-trips through the parser', () => {
    const d = diagramFrom(SHOP, 'postgresql');
    const out = generateSchema(d);
    const back = parseSql(out.script, 'postgresql');
    expect(back.errors).toEqual([]);
    expect(back.tables.map((t) => t.name).sort()).toEqual(['customers', 'orders']);
    const orders = back.tables.find((t) => t.name === 'orders')!;
    expect(orders.foreignKeys).toHaveLength(1);
    expect(orders.columns.find((c) => c.name === 'id')?.autoIncrement).toBe(true);
    expect(orders.indexes[0].name).toBe('idx_orders_customer');

    d.dialect = 'mariadb';
    const out2 = generateSchema(d);
    const back2 = parseSql(out2.script, 'mariadb');
    expect(back2.errors).toEqual([]);
    expect(back2.tables.find((t) => t.name === 'orders')!.foreignKeys).toHaveLength(1);
  });

  it('breaks reference cycles with ALTER TABLE', () => {
    const d = diagramFrom(
      `CREATE TABLE a (id INT PRIMARY KEY, b_id INT);
       CREATE TABLE b (id INT PRIMARY KEY, a_id INT);
       ALTER TABLE a ADD CONSTRAINT a_b FOREIGN KEY (b_id) REFERENCES b(id);
       ALTER TABLE b ADD CONSTRAINT b_a FOREIGN KEY (a_id) REFERENCES a(id);`,
      'postgresql',
    );
    const { deferred } = orderTables(d);
    expect(deferred.size).toBe(1);
    const out = generateSchema(d);
    expect(out.statements.filter((s) => s.startsWith('ALTER TABLE'))).toHaveLength(1);
    expect(out.statements.filter((s) => s.startsWith('CREATE TABLE'))).toHaveLength(2);
    const back = parseSql(out.script, 'postgresql');
    expect(back.errors).toEqual([]);
    expect(back.tables.flatMap((t) => t.foreignKeys)).toHaveLength(2);
  });

  it('quotes identifiers that need it and de-duplicates constraint names', () => {
    const d = diagramFrom(
      `CREATE TABLE "User" ("Order" INT PRIMARY KEY, "select" TEXT);
       CREATE TABLE x (id INT PRIMARY KEY, u1 INT REFERENCES "User", u2 INT REFERENCES "User");`,
      'postgresql',
    );
    const out = generateSchema(d);
    expect(out.script).toContain('CREATE TABLE "User" (');
    expect(out.script).toContain('"Order" INT PRIMARY KEY');
    expect(out.script).toContain('"select" TEXT');
    expect(out.script).toContain('CONSTRAINT "fk_x_User"');
    expect(out.script).toContain('CONSTRAINT "fk_x_User_2"');
  });

  it('documents data-flow links and tagged queries as comments', () => {
    const d = diagramFrom(`CREATE TABLE src (id INT PRIMARY KEY); CREATE TABLE dst (id INT PRIMARY KEY);`, 'postgresql');
    d.relationships.push(
      createRelationship({
        kind: 'flow',
        name: 'rollup',
        sourceTableId: d.tables[0].id,
        sourceColumnIds: [],
        targetTableId: d.tables[1].id,
        targetColumnIds: [],
        query: 'INSERT INTO dst SELECT id FROM src;',
      }),
    );
    const out = generateSchema(d);
    expect(out.statements).toHaveLength(2);
    expect(out.script).toContain('-- src -> dst (rollup)');
    expect(out.script).toContain('--   INSERT INTO dst SELECT id FROM src;');
  });

  it('generates per-table SQL and drop statements', () => {
    const d = diagramFrom(SHOP, 'postgresql');
    const orders = d.tables.find((t) => t.name === 'orders')!;
    expect(generateTableSql(d, orders.id)).toContain('FOREIGN KEY (customer_id) REFERENCES customers (id)');
    const drops = generateDropStatements(d);
    expect(drops[0]).toBe('DROP TABLE IF EXISTS orders CASCADE;');
    expect(drops[1]).toBe('DROP TABLE IF EXISTS customers CASCADE;');
    d.dialect = 'mariadb';
    const drops2 = generateDropStatements(d);
    expect(drops2[0]).toBe('SET FOREIGN_KEY_CHECKS = 0;');
    expect(drops2[drops2.length - 1]).toBe('SET FOREIGN_KEY_CHECKS = 1;');
  });
});

describe('translateType', () => {
  it('maps common types both ways', () => {
    expect(translateType('SERIAL', 'postgresql', 'mariadb')).toBe('INT');
    expect(translateType('TIMESTAMPTZ', 'postgresql', 'mariadb')).toBe('TIMESTAMP');
    expect(translateType('TIMESTAMP', 'postgresql', 'mariadb')).toBe('DATETIME');
    expect(translateType('JSONB', 'postgresql', 'mariadb')).toBe('JSON');
    expect(translateType('TEXT[]', 'postgresql', 'mariadb')).toBe('JSON');
    expect(translateType('character varying(80)', 'postgresql', 'mariadb')).toBe('VARCHAR(80)');
    expect(translateType('INT UNSIGNED', 'mariadb', 'postgresql')).toBe('BIGINT');
    expect(translateType('TINYINT(1)', 'mariadb', 'postgresql')).toBe('BOOLEAN');
    expect(translateType('DATETIME', 'mariadb', 'postgresql')).toBe('TIMESTAMP');
    expect(translateType('LONGTEXT', 'mariadb', 'postgresql')).toBe('TEXT');
    expect(translateType('DECIMAL(10,2)', 'mariadb', 'postgresql')).toBe('NUMERIC(10,2)');
    expect(translateType('VARCHAR(255)', 'mariadb', 'postgresql')).toBe('VARCHAR(255)');
    expect(translateType('SOMETHING_ODD', 'mariadb', 'postgresql')).toBe('SOMETHING_ODD');
  });
});
